version: "3.8"
services:
  postgres:
    image: itssoumen/postgresql-server
    environment:
      POSTGRES_USER: diploma
      POSTGRES_PASSWORD: 11111111
      TZ: "Europe/Minsk"
      PGTZ: "Europe/Minsk"
    command: postgres -c max_connections=1000
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5